server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Все маршруты отдаём index.html — React Router сам разберётся
        try_files $uri $uri/ /index.html;
    }

    # Кешируем статику (js, css, картинки)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}